- static/upload_image.json
> remove-public

- src/pages/audio_video/audio/index.md
* Update URLs, request/response syntax to be accurate to v2
* Make curl commands a bit more ergonomic by using (and explaining how to set) ENV variables for CLIENT_ID and ACCESS_TOKEN
* Tweak API family name to be correct
> Update Enhance Speech API guide for v2.

- src/pages/firefly-api/guides/changelog/index.md
- static/generate_similar_v3.json
- static/generative_fill_v3.json
- static/image_generation_v3.json
> remove-preview

- src/pages/firefly-api/guides/concepts/terminology.md
Provided two test text updates
- [ X] Bug fix (non-breaking change which fixes an issue)
- [X ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ X] My code follows the code style of this project.
- [ X] I have updated the documentation accordingly.
- [ X] I have read the **CONTRIBUTING** document.
> Fix minor typos

- src/pages/firefly-api/guides/index.md
> remove parenthesis in getting started

- src/pages/firefly-api/guides/index.md
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ x] My code follows the code style of this project.
- [x ] I have updated the documentation accordingly.
- [ x] I have read the **CONTRIBUTING** document.
- [x ] I have added tests to cover my changes.
- [ x] All new and existing tests passed.
> Remove second parenthetical

- src/pages/firefly-api/guides/concepts/terminology.md
- [ x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x ] My code follows the code style of this project.
- [x ] I have updated the documentation accordingly.
- [ x] I have read the **CONTRIBUTING** document.
- [ x] I have added tests to cover my changes.
- [ x] All new and existing tests passed.
> text change

- src/pages/firefly-api/guides/concepts/terminology.md
- src/pages/firefly-api/guides/how-tos/using-async-apis.md
- static/image_generation_v3.json
> Add async guide

- src/pages/firefly-api/guides/how-tos/using-async-apis.md
> Fix wording

- static/openapi_redocly_test.json
> add test json from eng

- static/openapi_redocly_test.json
> latest json to test

- static/generate_object_composite_v3.json
- static/generative_expand_v3.json
- static/generative_fill_v3.json
> Remove preview from gen oc, expand and gen fill

- src/pages/firefly-api/guides/changelog/index.md
> add october in

- src/pages/firefly-api/guides/api/generate-object-composite/index.md
> Fix object composite link from changelog

- static/async_redocly_test.json
> add json to test

- src/pages/firefly-api/guides/how-tos/using-expand-image.md
Removes stg from IMS login.
Corrects scopes.
Removes /output from complete source code.
Uses webp for mimetype for upload
- [x ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ x] My code follows the code style of this project.
- [ x] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
- [ x] I have read the **CONTRIBUTING** document.
- [ x] I have added tests to cover my changes.
- [ x] All new and existing tests passed.
> Fix issues in guide found by Mike Majzoub

- gatsby-config.js
> remove preview from m3

- src/pages/photoshop/concepts/index.md
- src/pages/photoshop/features/index.md
> fix grammar in concepts

- README.md
> fix readme so devs can run locally

- src/pages/firefly-api/guides/concepts/authentication/index.md
- src/pages/firefly-api/guides/concepts/rate-limits/index.md
> Rate Limits Docs Update

- static/upload_image.json
> Add expiry for uploaded assets

- src/pages/firefly-api/guides/how-tos/using-style-structure-refs.md
> Reword for present tense

- src/pages/photoshop/how-tos/smart-objects/smart-objects.md
- src/pages/photoshop/how-tos/text/text.md
> Add code samples to text and smart object tutorials

- src/pages/photoshop/code-sample/index.md
- src/pages/photoshop/how-tos/photoshop-actions/index.md
> remove duplicate code samples

- src/pages/photoshop/code-sample/index.md
- src/pages/photoshop/how-tos/smart-objects/index.md
> Move code samples for smart objects to tutorial

- src/pages/firefly-api/guides/how-tos/using-async-apis.md
> improvements

- src/pages/guides/quickstart/index.md
> FFS Quickstart overview

- README.md
- gatsby-config.js
- src/pages/guides/get-started.md
Due to documented SDK issues, we are hiding the guide.
> Hide SDK guide and link

- gatsby-config.js
- src/pages/guides/quickstart/index.md
> Changing Headers to sentence case

- src/pages/indesign-apis/index.md
> Update index.md for API hyperlinks

- gatsby-config.js
- static/generative_expand.json
- static/generative_fill.json
- static/image_generation.json
> Added Matt's API deprecations

- src/pages/indesign-apis/api/status.md
- src/pages/indesign-apis/index.md
- static/indesign/capabilitiesapi.json
- static/indesign/components/responses/TooManyRequests.yaml
- static/indesign/datamergeapi.json
- static/indesign/renditionapi.json
- static/indesign/statusapi.json
This Pr is in context with the following changes:
- Removed the status api from Custom Capability Tab and added a new Tab for it.
- Added error code 429 in each of the API.
> Error Code and Status Call Changes

- static/generate_object_composite_async_v3.json
- static/generate_similar_async_v3.json
- static/generative_expand_async_v3.json
- static/generative_fill_async_v3.json
- static/image_generation_async_v3.json
> Added AccessToken to async API header params (issue#116)

- src/pages/guides/index.md
> Add InDesign to Services index.md

- .github/workflows/deploy.yml
> Update deploy.yml with actions v3

- .github/workflows/deploy.yml
> Update deploy.yml with v3

- src/pages/audio-video-api/guides/index.md
> Update quickstart with endpoint version v1

- static/indesign/capabilitiesapi.json
- static/indesign/components/responses/TooManyRequests.yaml
- static/indesign/datamergeapi.json
- static/indesign/renditionapi.json
- static/indesign/statusapi.json
Error code 429 title update
This is a copy of Rhythmn Jain's PR to the InDesign branch[, Error Code Changes #129](https://github.com/AdobeDocs/ff-services-docs/pull/129), except merging with main.
> Error Code Changes

- gatsby-config.js
- src/pages/guides/index.md
> Added ADLS access

- gatsby-config.js
- src/pages/guides/index.md
ADLS should not be used on public docs. Changing this to TLS (abreviating Translate and lip sync).
> Change ADLS to TLS

- src/pages/audio-video-api/getting_started/usage.md
Updated the usage notes with new limits.
> Fix for issue 142

- src/pages/firefly-api/guides/how-tos/cm-share-model/index.md
Updated video link for youtube re-upload.
> youtube vid update and links

- static/async_redocly_test.json
- static/generate_object_composite_async_v3.json
- static/generate_similar_async_v3.json
- static/generative_expand_async_v3.json
- static/generative_fill_async_v3.json
- static/image_generation_async_v3.json
- static/openapi_redocly_test.json
https://jira.corp.adobe.com/browse/CENT-2591
> corrected the success status enum for GET Result APIs

- static/audio-video/reframe-oas-v1.json
> CENT-2643 Fix API Position param and GET 200 response objects labeling

- static/api_response_400_error_schema.json
- static/api_response_402_error_schema.json
- static/api_response_403_error_schema.json
- static/api_response_404_error_schema.json
- static/api_response_409_error_schema.json
- static/photoshop_productCrop.json
https://jira.corp.adobe.com/browse/CENT-2668
> Fixed spelling error and error schema definitions

- src/pages/audio-video-api/guides/index.md
> review of the Reframe quickstart

- src/pages/firefly-api/guides/concepts/custom-models/index.md
https://jira.corp.adobe.com/browse/CENT-3082
> Fixed the described supported custom models- removed

- src/pages/indesign-apis/Help/index.md
- src/pages/indesign-apis/how-tos/working-with-datamerge-api/index.md
- static/indesign/scriptsapi.json
Reverts AdobeDocs/ff-services-docs#171
> Revert "Datamerge Output Documentation and Adding Help Information"

- gatsby-config.js
https://jira.corp.adobe.com/browse/CENT-2762
> Changed Audio/Video header tab URL

- static/generate_similar_async_v3.json
- static/generative_expand_async_v3.json
- static/generative_fill_async_v3.json
- static/image_generation_async_v3.json
https://jira.corp.adobe.com/browse/CENT-2642
> Added 413 error code

- src/pages/firefly-api/guides/concepts/structure-image-reference/index.md
- src/pages/firefly-api/guides/concepts/style-image-reference/index.md
https://jira.corp.adobe.com/browse/CENT-3158
> Cent 3158/update struct image

- .cursor/rules/cursor-rules.mdc
- .cursor/rules/docs-lint.mdc
- .cursor/rules/gatsby-config.mdc
- .cursor/rules/getting-started-docs.mdc
> Added cursor rules folder and initial rulesets

- src/pages/firefly-api/guides/concepts/style-presets/index.md
https://jira.corp.adobe.com/browse/CENT-3160
> [Cent 3160] Update style presets endpoints

- static/photoshop_applyPsdEdits.json
- [X ] Doc bug fix (non-breaking change which fixes an issue, like a typo)
Correcting a typo brought up in SLack: https://creativecloud.slack.com/archives/CCAEDS6J2/p1749051144370299
> fixed typo in Ps Appy Edits

- static/indesign/statusapi.json
Adding partial_success schema changes
> Status API changes for partial success

- gatsby-config.js
- src/pages/guides/index.md
This PR adds Substance 3d API to the headers top bar and creates a Substance API tile on the Services Overview page.'
https://jira.corp.adobe.com/browse/CENT-2385
> CENT-2385 Substance 3d/add for ga

- gatsby-config.js
- src/pages/guides/index.md
> Fixed Substance links

- .github/workflows/deploy.yml
> Update deploy.yml with photoshop exclusion

- static/generate_video_api.json
https://jira.corp.adobe.com/browse/FFENT-1166
> Added clip duration (5 sec) to the Generate Video API description

- src/pages/firefly-api/guides/how-tos/cm-generate-image/index.md
Updated Get Result and response Paths to exclude stage paths, and use dummy paths instead
https://jira.corp.adobe.com/browse/FFENT-1217
> [FFENT-1217] Exclude stage paths from Get response examples

- src/pages/indesign-apis/changelog/index.md
- src/pages/indesign-apis/concepts/index.md
- src/pages/indesign-apis/help/usage_notes/index.md
- static/indesign/datamergeapi.json
- static/indesign/statusapi.json
> Changes for upcoming prod deployment

- yarn.lock
Fix yarn.lock after removing cis-photoshop-api dependency
> Fix yarn.lock after removing cis-photoshop-api dependency

- src/pages/firefly-api/index.md
> Updated Image API overview page links to V3_async API

- .github/workflows/auto-deploy.yml
- .github/workflows/deploy.yml
- gatsby-config.js
Updates for repo changeover:
- added indesign-apis to excludeSubfolder for manual AND to deploy workflows
- removed inDesign section from gatsby config and rerouted the path to the spoke repo
> Changeover to InDesign spoke repo
